"""isoformated_time_added

Revision ID: db2a8406d16b
Revises: 
Create Date: 2023-11-25 20:47:41.777118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db2a8406d16b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploadClock', sa.DateTime(), nullable=True))
        batch_op.drop_column('uploadedClock')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploadedClock', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_column('uploadClock')

    # ### end Alembic commands ###
